spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    tomcat:
      initial-size: 2
      min-idle: 5
      max-idle: 10
      max-active: 20
      max-wait: 60000
  jpa:
    hibernate:
#     更新或者创建数据表结构
      ddl-auto: update
#   控制台显示SQL
    show-sql: true
    properties:
      hibernate.format_sql: true
